corrin/jobs_manager_front

docs/jobs_aging_report_plan.md
src/router/index.ts
src/services/job-aging-report.service.ts
src/types/job-aging.types.ts
src/views/JobAgingReportView.vue

Job Aging report

---

src/components/AppNavbar.vue

Add job aging to the menu

---

CLAUDE.md
src/components/purchasing/ReceivedItemsTable.vue
src/views/purchasing/StockView.vue

Try to allow negative stock allocation

---

scripts/deploy_frontend.sh

vite.service is a one-shot build service. After npm run build completes, only nginx needs to be reloaded to serve the new static files.
- …

fix(deploy): remove unnecessary service restart, only reload nginx

---

schema.yml
src/api/generated/api.ts
src/components/ConfirmModal.vue
src/components/job/JobQuotingChatTab.vue
src/components/job/JobViewTabs.vue
src/services/aiProviderService.ts
src/services/quote-chat.service.ts
src/views/AdminAIProvidersView.vue
src/views/AdminStaffView.vue

Chatbot bugfix

---

src/components/timesheet/StaffRow.vue
src/components/timesheet/StaffWeekRow.vue
src/views/DailyTimesheetView.vue
src/views/WeeklyTimesheetView.vue

style(timesheet): adjust component styling for improved responsiveness and visual consistency
This commit refactors the styling of `StaffRow.vue`, `StaffWeekRow.vue`, `DailyTimesheetView.vue`, and `WeeklyTimesheetView.vue` to enhance their responsiveness across different screen sizes and improve overall visual consistency.
Changes include:
- **Responsive Spacing:** Adjusted `space-y`, `space-x`, `gap`, `px`, `py`, `mb`, and `mt` values using responsive classes (e.g., `sm:`, `lg:`) to ensure elements are appropriately spaced on mobile, tablet, and desktop views.
- **Font Sizes:** Modified `text-xs`, `text-sm`, `text-base`, `text-lg`, `text-xl`, `text-2xl`, `text-3xl` classes with responsive prefixes to scale text sizes gracefully.
- **Element Dimensions:** Updated `h-`, `w-` classes for …

Refactor: make timesheets more compact

---

package.json
src/components/job/JobActualTab.vue

Reverts corrin/jobs_manager_front#74

Revert "feat: add quote chip to banner and fix schema formatting"

---

README.md
src/components/job/JobActualTab.vue
vite.config.ts

Reverts corrin/jobs_manager_front#72

Revert "fix: clarify invoice button text based on pricing methodology"

---

package.json
src/components/job/JobActualTab.vue

Adds Quote chip between Estimate and Time & Expenses for fixed price jobs. Also fixes schema formatting.

feat: add quote chip to banner and fix schema formatting

---

src/views/JobCreateView.vue

Updates UI labels from 'Pricing Methodology' to 'Pricing Method'

fix: change 'Pricing Methodology' to 'Pricing Method' in UI labels

---

.gitignore
README.md
package.json
src/components/job/JobActualTab.vue
src/components/job/JobQuoteTab.vue
src/components/job/JobViewTabs.vue
src/views/JobCreateView.vue
src/views/JobView.vue
vite.config.ts

Accept Quote button now changes job status to 'approved' when clicked

fix: accept quote button updates job status to approved

---

src/components/purchasing/PoLinesTable.vue
src/components/shared/SmartCostLinesTable.vue
src/views/purchasing/ItemSelect.vue

This PR addresses the problems in the following tickets:
- [Jobs Manager Screen Expanding by Itself](https://trello.com/c/pmYPTwKN/106-job-manager-screen-expanding-by-itself-cannot-see-the-whole-screen-now-bottom-slider-missing)
- [Remove the up and down arrows on dollar entry](https://trello.com/c/DLEkZxTc/99-remove-the-up-and-down-arrow-on-dollar-entry)
---
- It also focused on enhancing the `ItemSelect` UX by showing additional info like quantity, item code and unit price.

Refactor: improve lines table UX

---

src/components/job/JobActualTab.vue
src/components/job/JobEstimateTab.vue
src/components/shared/SmartCostLinesTable.vue
src/views/purchasing/ItemSelect.vue

Attempted bugfix

---

.gitignore
package-lock.json
package.json
scripts/analyze_captures.cjs
scripts/capture_metrics.cjs

Emergency single stock fetch

---

src/components/StaffAvatar.vue

Single serialiser

---

schema.yml
src/api/generated/api.ts
src/components/job/JobSettingsTab.vue
src/composables/useJobFinancials.ts
src/views/DataQualityArchivedJobsView.vue
src/views/JobView.vue

Sort of issues

---

src/views/JobCreateView.vue

Split shop and office time

---

src/composables/useContactManagement.ts

bugfix to contact management

---

eslint.config.ts
src/components/job/JobActualTab.vue
src/components/job/JobEstimateTab.vue
src/components/job/JobQuoteTab.vue
src/composables/useAddEmptyCostLine.ts
src/composables/useAddMaterialCostLine.ts
src/composables/useCostLinesActions.ts
src/composables/useCostSummary.ts
src/composables/useCreateCostLineFromEmpty.ts
src/composables/useSmartCostLineDelete.ts

Refactor to common stuff between estimate and quote

---

schema.yml
src/api/generated/api.ts
src/utils/string-formatting.ts
src/views/DataQualityArchivedJobsView.vue

Added better archiving report
